document.addEventListener("DOMContentLoaded", async () => {
  const auth=window.actionBuyerAuth;if(!auth)return;const session=await auth.getSession();if(!session){window.location.href="login.html";return;}
  const{data:staffRow}=await auth.supabase.from("staff_users").select("user_id").eq("user_id",session.user.id).maybeSingle();if(staffRow){window.location.href="admin.html";return;}
  document.querySelectorAll("[data-account-link]").forEach(link=>{link.textContent="My Account";link.href="account.html";});
  const user=session.user,money=n=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(Number(n||0)),esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"),offersBox=document.getElementById("offers"),valuationsBox=document.getElementById("valuations"),welcome=document.getElementById("welcome-text"),signOut=document.getElementById("sign-out");
  const{data:profile}=await auth.supabase.from("profiles").select("full_name,account_number,phone,address_line1,address_line2,city,county,postcode").eq("id",user.id).maybeSingle();
  if(welcome)welcome.textContent=profile?.full_name?.trim()?`Welcome, ${profile.full_name.trim()}. Your account number is ${profile.account_number||"not yet assigned"}.`:`Welcome. Signed in as ${user.email}`;
  if(signOut)signOut.addEventListener("click",async()=>{signOut.disabled=true;try{await auth.signOut();}catch(e){signOut.disabled=false;alert(e?.message||"Could not sign out. Please try again.");}});
  async function sendEmailForOffer(offerId,eventType){try{await auth.supabase.functions.invoke("send-quote-email-v2",{body:{offer_id:offerId,event_type:eventType}});}catch(_){} }
  function quoteTotal(valuationItems,allOffers){return valuationItems.reduce((sum,item)=>{const o=allOffers.filter(x=>x.item_id===item.id&&["published","accepted"].includes(x.status)).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0];return sum+(Number(o?.amount)||0);},0);}
  async function load(){if(offersBox)offersBox.innerHTML="<p>Loading...</p>";if(valuationsBox)valuationsBox.innerHTML="<p>Loading...</p>";
    const{data:valuations,error}=await auth.supabase.from("valuations").select("id,quote_reference,status,manufacturer,model,package,condition,quote_amount,submitted_at,updated_at,quote_data").eq("user_id",user.id).order("submitted_at",{ascending:false});
    if(error){if(valuationsBox)valuationsBox.innerHTML="<p>We couldn't load your valuations right now.</p>";if(offersBox)offersBox.innerHTML="<p>We couldn't load your offers right now.</p>";return;}
    if(!valuations?.length){if(valuationsBox)valuationsBox.innerHTML='<div class="empty-account"><h3>No valuations yet</h3><p>When you submit a valuation, it will appear here.</p><a class="btn btn-primary" href="quote.html">GET A VALUATION</a></div>';if(offersBox)offersBox.innerHTML="<p>No active offers yet.</p>";return;}
    const ids=valuations.map(v=>v.id);const{data:items}=await auth.supabase.from("quote_items").select("id,valuation_id,item_name,manufacturer,model,package,item_status,item_position").in("valuation_id",ids);const itemIds=(items||[]).map(i=>i.id);const{data:offers}=itemIds.length?await auth.supabase.from("quote_offers").select("id,item_id,offer_type,amount,status,customer_message,published_at,responded_at,created_at").in("item_id",itemIds).order("created_at",{ascending:false}):{data:[]};
    const activeQuotes=valuations.map(v=>{const its=(items||[]).filter(i=>i.valuation_id===v.id).sort((a,b)=>(a.item_position||999)-(b.item_position||999));const os=(offers||[]).filter(o=>its.some(i=>i.id===o.item_id));const pending=its.some(i=>i.item_status!=="refused"&&i.item_status!=="closed"&&os.some(o=>o.item_id===i.id&&o.status==="published"));return{v,its,os,total:quoteTotal(its,os),pending};}).filter(x=>x.pending);
    if(offersBox)offersBox.innerHTML=activeQuotes.length?activeQuotes.map(({v,its,os,total})=>`<section class="account-panel" style="margin-bottom:1.25rem;"><div class="section-heading"><p class="section-kicker">QUOTE</p><h2>${esc(v.quote_reference)}</h2><p>Review each item separately. Your total updates as you accept or refuse offers.</p></div><div>${its.map(item=>{const current=os.filter(o=>o.item_id===item.id&&["published","accepted","refused"].includes(o.status)).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0];const offered=current&&["published","accepted"].includes(current.status);const status=item.item_status||"under_assessment";return `<article class="valuation-card offer-card"><div><span class="valuation-ref">ITEM ${esc(item.item_position||"")}</span><p class="section-kicker">${esc(String(status).replaceAll("_"," "))}</p><h3>${esc(item.item_name||item.model||"Equipment")}</h3><p>${esc(item.manufacturer||"")}${item.package?" — "+esc(item.package):""}</p>${current?.customer_message?`<p>${esc(current.customer_message)}</p>`:""}</div><div class="valuation-meta">${offered?`<strong>${money(current.amount)}</strong>`:status==="refused"?`<span class="status-badge">REFUSED</span>`:`<span class="status-badge">AWAITING OFFER</span>`}${current?.status==="accepted"?`<span class="status-badge">ACCEPTED</span>`:""}${current?.status==="published"?`<div class="navigation-buttons"><button class="btn btn-primary accept-offer" data-id="${current.id}">ACCEPT</button><button class="btn btn-secondary refuse-offer" data-id="${current.id}">REFUSE</button></div>`:""}</div></article>`;}).join("")}</div><div class="quote-basket-total" style="display:flex;justify-content:space-between;padding:1rem 0;border-top:2px solid #102f4f;margin-top:1rem;font-size:1.2rem;"><strong>Current total offer</strong><strong>${money(total)}</strong></div></section>`).join(""):"<p>No offers currently require your response. Accepted items are shown in your purchase summary.";
    if(valuationsBox){const pendingValuations=valuations.filter(v=>(items||[]).filter(i=>i.valuation_id===v.id).some(i=>!['accepted','closed'].includes(i.item_status)));valuationsBox.innerHTML=pendingValuations.length?pendingValuations.map(v=>{const its=(items||[]).filter(i=>i.valuation_id===v.id);const date=v.submitted_at?new Date(v.submitted_at).toLocaleDateString("en-GB"):"";const ready=its.filter(i=>i.item_status==="accepted").length;return `<article class="valuation-card"><div><span class="valuation-ref">${esc(v.quote_reference)}</span><p class="section-kicker">VALUATION REQUEST</p><h3>${its.length} item${its.length===1?"":"s"}</h3><p>${its.map(i=>esc(i.item_name||i.model||"Equipment")).join(" · ")}</p></div><div class="valuation-meta"><span class="status-badge">${ready}/${its.length} accepted</span><small>Submitted ${date}</small></div></article>`;}).join(""):"<p>No outstanding valuation requests.";}
    document.querySelectorAll(".accept-offer").forEach(btn=>btn.addEventListener("click",async()=>{btn.disabled=true;const{error}=await auth.supabase.rpc("accept_quote_offer",{p_offer_id:btn.dataset.id});if(error){alert(error.message||"The offer could not be accepted.");btn.disabled=false;return;}await sendEmailForOffer(btn.dataset.id,"offer_accepted");await load();}));
    document.querySelectorAll(".refuse-offer").forEach(btn=>btn.addEventListener("click",async()=>{if(!confirm("Refuse this item?"))return;btn.disabled=true;const{error}=await auth.supabase.rpc("refuse_quote_offer",{p_offer_id:btn.dataset.id});if(error){alert(error.message||"The offer could not be refused.");btn.disabled=false;return;}await sendEmailForOffer(btn.dataset.id,"offer_refused");await load();}));
  }
  await load();
});