document.addEventListener("DOMContentLoaded", async () => {
  const auth=window.actionBuyerAuth; const session=await auth.getSession();
  if(!session){location.href="login.html?return=admin-catalog.html";return;}
  const {data:staff}=await auth.supabase.from("staff_users").select("user_id").eq("user_id",session.user.id).maybeSingle();
  if(!staff){document.body.innerHTML='<main class="account-page"><div class="container"><h1>Staff access required</h1></div></main>';return;}
  const form=document.getElementById("catalog-form"), list=document.getElementById("catalog-list"), msg=document.getElementById("catalog-message"), search=document.getElementById("search");
  let rows=[];
  const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
  const money=v=>v==null?"—":new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(Number(v));
  const setMsg=(t,ok=true)=>{msg.textContent=t;msg.className="form-message "+(ok?"success":"error");};
  const num=id=>{const v=document.getElementById(id).value.trim();return v===""?null:Number(v);};
  function fill(r){document.getElementById("product-id").value=r.id;document.getElementById("category").value=r.category;document.getElementById("manufacturer").value=r.manufacturer;document.getElementById("model").value=r.model;document.getElementById("package-key").value=r.package_key;document.getElementById("package-name").value=r.package_name;document.getElementById("factory-sealed").value=r.factory_sealed_price??"";document.getElementById("opened-unused").value=r.opened_unused_price??"";document.getElementById("excellent").value=r.excellent_price??"";document.getElementById("good").value=r.good_price??"";document.getElementById("fair").value=r.fair_price??"";document.getElementById("active").checked=!!r.active;document.getElementById("notes").value=r.notes||"";window.scrollTo({top:0,behavior:"smooth"});}
  function clear(){form.reset();document.getElementById("product-id").value="";document.getElementById("package-key").value="standard";document.getElementById("package-name").value="Standard Package";document.getElementById("active").checked=true;}
  function render(){const q=search.value.trim().toLowerCase();const data=rows.filter(r=>!q||[r.category,r.manufacturer,r.model,r.package_name].some(v=>String(v||"").toLowerCase().includes(q)));if(!data.length){list.innerHTML="<p>No catalogue products found.</p>";return;}list.innerHTML=data.map(r=>`<article class="valuation-card" style="margin:.75rem 0;"><div><span class="valuation-ref">${esc(r.manufacturer)} ${esc(r.model)}</span><p>${esc(r.category)} · ${esc(r.package_name)} ${r.active?"":"· INACTIVE"}</p><p>Sealed ${money(r.factory_sealed_price)} · Unused ${money(r.opened_unused_price)} · Excellent ${money(r.excellent_price)} · Good ${money(r.good_price)} · Fair ${money(r.fair_price)}</p></div><div><button class="btn btn-secondary edit" data-id="${r.id}" type="button">EDIT</button></div></article>`).join("");list.querySelectorAll(".edit").forEach(b=>b.onclick=()=>fill(rows.find(r=>r.id===b.dataset.id)));}
  async function load(){const {data,error}=await auth.supabase.from("quote_catalog_products").select("*").order("manufacturer").order("model").order("package_name");if(error){setMsg(error.message,false);return;}rows=data||[];render();}
  form.onsubmit=async e=>{e.preventDefault();const payload={p_id:document.getElementById("product-id").value||null,p_category:document.getElementById("category").value,p_manufacturer:document.getElementById("manufacturer").value,p_model:document.getElementById("model").value,p_package_key:document.getElementById("package-key").value,p_package_name:document.getElementById("package-name").value,p_factory_sealed_price:num("factory-sealed"),p_opened_unused_price:num("opened-unused"),p_excellent_price:num("excellent"),p_good_price:num("good"),p_fair_price:num("fair"),p_active:document.getElementById("active").checked,p_notes:document.getElementById("notes").value};const {error}=await auth.supabase.rpc("staff_upsert_catalog_product",payload);if(error){setMsg(error.message,false);return;}setMsg("Product saved.");clear();await load();};
  document.getElementById("clear-form").onclick=clear;search.oninput=render;await load();
});