(function(){
'use strict';let currentMailbox='default',currentFolder='INBOX',selectedUid=null,mailboxes=[],currentMessage=null,showPlain=false,mailManager=false;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const addr=a=>(a||[]).map(x=>x.name?x.name+' <'+x.address+'>':x.address).join(', ');
const fmtDate=v=>{try{return v?new Date(v).toLocaleString('en-GB',{dateStyle:'short',timeStyle:'short'}):''}catch(_){return ''}};
function notice(t,bad=false){const e=$('mail-message');e.textContent=t||'';e.className='form-message '+(bad?'error':'success');}
async function api(action,payload={}){const sb=window.actionBuyerAuth?.supabase;if(!sb)throw Error('Secure connection unavailable.');const {data,error}=await sb.functions.invoke('management-mail-v2',{body:{action,...payload}});if(error){let message=data?.error||error.message||'Mail operation failed.';try{const response=error.context;if(response?.clone){const detail=await response.clone().json();message=detail?.error||detail?.message||message;}}catch(_){}throw Error(message);}if(data?.error)throw Error(data.error);return data;}
async function guard(){const a=window.actionBuyerAuth,s=await a.getSession();if(!s){location.href='staff-login.html';return false;}const {data}=await a.supabase.from('staff_users').select('active,can_manage_staff,can_access_mail').eq('user_id',s.user.id).maybeSingle();if(!data?.active||(!data.can_manage_staff&&!data.can_access_mail)){location.href='admin.html';return false;}mailManager=!!data.can_manage_staff;return true;}
function activeBox(){return mailboxes.find(x=>String(x.id)===String(currentMailbox))||mailboxes[0];}
async function loadMailboxes(){const d=await api('mailboxes');mailboxes=d.mailboxes||[];const sel=$('mailbox-select');sel.innerHTML=mailboxes.map(b=>'<option value="'+esc(b.id)+'">'+esc(b.display_name||b.email_address)+' — '+esc(b.email_address)+'</option>').join('');if(!mailboxes.some(b=>String(b.id)===String(currentMailbox)))currentMailbox=mailboxes[0]?.id||'default';sel.value=currentMailbox;const b=activeBox();$('mailbox-summary').innerHTML='<strong>'+esc(b?.display_name||'Business mailbox')+'</strong><span>'+esc(b?.email_address||'')+'</span>';$('compose-from-label').textContent='New message from '+(b?.email_address||'business mailbox');}
async function loadFolders(){const box=activeBox();$('mail-folders').innerHTML='<p style="padding:.5rem;color:#71808d">Loading folders...</p>';if(!box?.imapConfigured){$('mail-folders').innerHTML='<p style="padding:.5rem;color:#9a5a10;font-size:.82rem">Inbox connection pending for this mailbox.</p>';return;}const d=await api('folders',{mailbox_id:currentMailbox});const fs=d.folders||[];$('mail-folders').innerHTML='';fs.forEach(f=>{const b=document.createElement('button');b.type='button';b.className='mail-folder'+(f.path===currentFolder?' active':'');b.textContent=f.name;b.onclick=()=>{currentFolder=f.path;selectedUid=null;document.querySelectorAll('.mail-folder').forEach(x=>x.classList.toggle('active',x===b));loadMessages();};$('mail-folders').appendChild(b);});if(!fs.some(f=>f.path===currentFolder))currentFolder=fs[0]?.path||'INBOX';}
async function loadMessages(){const list=$('mail-list'),box=activeBox();$('mail-folder-title').textContent=currentFolder;$('mail-count').textContent='';if(!box?.imapConfigured){list.innerHTML='<div class="mail-empty"><div><strong>Mailbox connection pending</strong><p>Credentials for this address have not been configured yet.</p></div></div>';return;}list.innerHTML='<p style="padding:1rem">Loading messages...</p>';try{const d=await api('messages',{mailbox_id:currentMailbox,folder:currentFolder});$('mail-count').textContent=(d.total||0)+' messages';if(!d.messages?.length){list.innerHTML='<div class="mail-empty"><div><strong>No messages</strong><p>This folder is empty.</p></div></div>';return;}list.innerHTML='';d.messages.forEach(m=>{const b=document.createElement('button');b.type='button';b.className='mail-item'+(!m.seen?' unread':'')+(selectedUid===m.uid?' active':'');b.innerHTML='<div class="mail-item-row"><span class="mail-item-from">'+esc(m.from?.[0]?.name||m.from?.[0]?.address||'Unknown')+'</span><span>'+esc(fmtDate(m.date))+'</span></div><div class="mail-item-subject">'+esc(m.subject)+'</div>';b.onclick=()=>openMessage(m.uid,b);list.appendChild(b);});}catch(e){list.innerHTML='<p style="padding:1rem">Unable to load messages.</p>';notice(e.message,true);}}
function firstAddress(a){return (a||[])[0]?.address||'';}
function safeHtml(html){const d=document.implementation.createHTMLDocument('email');d.body.innerHTML=String(html||'');d.querySelectorAll('script,iframe,object,embed,form,meta,base,link').forEach(x=>x.remove());d.querySelectorAll('*').forEach(el=>[...el.attributes].forEach(a=>{const n=a.name.toLowerCase(),v=String(a.value||'').trim().toLowerCase();if(n.startsWith('on')||((n==='href'||n==='src'||n==='action')&&(v.startsWith('javascript:')||v.startsWith('data:text/html'))))el.removeAttribute(a.name);}));return '<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;line-height:1.6;color:#26313b;padding:24px;margin:0;word-break:break-word}img{max-width:100%;height:auto}table{max-width:100%;border-collapse:collapse}pre{white-space:pre-wrap}a{color:#b36a16}</style></head><body>'+d.body.innerHTML+'</body></html>';}
function renderBody(){const body=$('mail-body');if(!currentMessage)return;body.innerHTML='';if(!showPlain&&currentMessage.html){const frame=document.createElement('iframe');frame.className='mail-html-frame';frame.setAttribute('sandbox','allow-popups');frame.srcdoc=safeHtml(currentMessage.html);body.appendChild(frame);$('mail-plain-toggle').textContent='PLAIN TEXT';}else{const pre=document.createElement('div');pre.className='mail-plain-body';pre.textContent=currentMessage.text||'(No readable message body supplied.)';body.appendChild(pre);$('mail-plain-toggle').textContent=currentMessage.html?'HTML VIEW':'PLAIN TEXT';}}
function renderAttachments(){const box=$('mail-attachments'),items=currentMessage?.attachments||[];box.hidden=!items.length;if(!items.length){box.innerHTML='';return;}box.innerHTML='<strong>Attachments</strong><div class="attachment-list"></div>';const list=box.querySelector('.attachment-list');items.forEach(a=>{const b=document.createElement('button');b.type='button';b.className='attachment';b.textContent=(a.filename||'Attachment')+' · '+Math.max(1,Math.round((a.size||0)/1024))+' KB';b.onclick=()=>downloadAttachment(a.index,a.filename||'attachment');list.appendChild(b);});}
async function downloadAttachment(index,name){try{notice('Downloading attachment...');const d=await api('attachment',{mailbox_id:currentMailbox,folder:currentFolder,uid:selectedUid,index});const bin=atob(d.content_base64||''),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);const url=URL.createObjectURL(new Blob([bytes],{type:d.content_type||'application/octet-stream'})),a=document.createElement('a');a.href=url;a.download=d.filename||name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);notice('');}catch(e){notice(e.message,true);}}
async function openMessage(uid,button){selectedUid=uid;currentMessage=null;showPlain=false;document.querySelectorAll('.mail-item').forEach(x=>x.classList.toggle('active',x===button));$('mail-compose-form').hidden=true;$('mail-reader-empty').hidden=true;$('mail-reader-content').hidden=false;$('mail-subject').textContent='Loading...';$('mail-from').textContent='';$('mail-meta').textContent='';$('mail-body').textContent='';$('mail-attachments').hidden=true;try{const d=await api('message',{mailbox_id:currentMailbox,folder:currentFolder,uid});currentMessage=d;$('mail-subject').textContent=d.subject||'(No subject)';$('mail-from').textContent='From: '+addr(d.from);$('mail-meta').textContent='To: '+addr(d.to)+(d.cc?.length?'\nCc: '+addr(d.cc):'')+'\n'+fmtDate(d.date);renderAttachments();renderBody();}catch(e){$('mail-body').textContent='Unable to open this message.';notice(e.message,true);}}
async function moveSelected(action){
 if(!selectedUid)return;
 const label=action==='archive'?'archive':'move to Trash';
 if(!confirm('Are you sure you want to '+label+' this email?'))return;
 const archive=$('mail-archive'),del=$('mail-delete');
 if(archive)archive.disabled=true;if(del)del.disabled=true;
 try{
  await api(action,{mailbox_id:currentMailbox,folder:currentFolder,uid:selectedUid});
  selectedUid=null;currentMessage=null;
  $('mail-reader-content').hidden=true;$('mail-reader-empty').hidden=false;
  notice(action==='archive'?'Email archived.':'Email moved to Trash.');
  await loadFolders();await loadMessages();
 }catch(e){notice(e.message,true);}
 finally{if(archive)archive.disabled=false;if(del)del.disabled=false;}
}
function compose(mode='new'){$('mail-reader-content').hidden=true;$('mail-reader-empty').hidden=true;$('mail-compose-form').hidden=false;$('compose-mode-label').textContent=mode==='reply'?'REPLY':mode==='forward'?'FORWARD':'NEW MESSAGE';if(mode==='new'){$('mail-compose-form').reset();}else if(currentMessage){if(mode==='reply'){$('compose-to').value=firstAddress(currentMessage.replyTo)||firstAddress(currentMessage.from);$('compose-subject').value=/^re:/i.test(currentMessage.subject||'')?currentMessage.subject:'Re: '+(currentMessage.subject||'');$('compose-text').value='\n\nOn '+fmtDate(currentMessage.date)+', '+addr(currentMessage.from)+' wrote:\n\n'+(currentMessage.text||'');}else{$('compose-to').value='';$('compose-subject').value=/^fwd:/i.test(currentMessage.subject||'')?currentMessage.subject:'Fwd: '+(currentMessage.subject||'');$('compose-text').value='\n\n---------- Forwarded message ----------\nFrom: '+addr(currentMessage.from)+'\nDate: '+fmtDate(currentMessage.date)+'\nSubject: '+(currentMessage.subject||'')+'\nTo: '+addr(currentMessage.to)+'\n\n'+(currentMessage.text||'');}}$('compose-to').focus();}
async function manager(){const [mb,st]=await Promise.all([api('mailboxes'),api('staff')]);const staff=$('new-mailbox-staff');staff.innerHTML='<option value="">Not assigned</option>'+(st.staff||[]).map(s=>'<option value="'+s.user_id+'">'+esc(s.display_name||s.username)+(s.business_email?' — '+esc(s.business_email):'')+'</option>').join('');$('mailbox-cards').innerHTML=(mb.mailboxes||[]).map(b=>'<div class="mailbox-card"><div><strong>'+esc(b.display_name||b.email_address)+'</strong><small>'+esc(b.email_address)+' · '+esc(b.mailbox_type)+'</small></div><div><span class="mailbox-state '+((b.smtpConfigured&&b.imapConfigured)?'':'pending')+'">'+((b.smtpConfigured&&b.imapConfigured)?'CONNECTED':'SETUP PENDING')+'</span>'+(String(b.id)!=='default'?'<button class="btn btn-secondary mail-small-remove" data-remove="'+esc(b.id)+'" type="button">REMOVE</button>':'')+'</div></div>').join('');}
document.addEventListener('DOMContentLoaded',async()=>{if(!await guard())return;if(!mailManager){const m=$('manage-mailboxes');if(m)m.hidden=true;}try{await loadMailboxes();await loadFolders();await loadMessages();}catch(e){notice(e.message,true);}
$('mailbox-select').onchange=async e=>{currentMailbox=e.target.value;currentFolder='INBOX';selectedUid=null;$('mail-reader-content').hidden=true;$('mail-reader-empty').hidden=false;await loadMailboxes();await loadFolders();await loadMessages();};
$('mail-refresh').onclick=async()=>{notice('');await loadFolders();await loadMessages();};$('mail-compose').onclick=()=>compose('new');$('mail-compose-side').onclick=()=>compose('new');$('mail-reply').onclick=()=>compose('reply');$('mail-forward').onclick=()=>compose('forward');$('mail-plain-toggle').onclick=()=>{showPlain=!showPlain;renderBody();};$('mail-archive').onclick=()=>moveSelected('archive');$('mail-delete').onclick=()=>moveSelected('delete');
$('mail-cancel-compose').onclick=()=>{$('mail-compose-form').hidden=true;$('mail-reader-empty').hidden=false;};
if(mailManager)$('manage-mailboxes').onclick=async()=>{$('mailbox-manager').hidden=false;await manager();};$('close-mailbox-manager').onclick=()=>{$('mailbox-manager').hidden=true;};
$('mailbox-cards').onclick=async e=>{const b=e.target.closest('[data-remove]');if(!b)return;if(!confirm('Remove this mailbox from GearCashOut?'))return;await api('remove_mailbox',{mailbox_id:b.dataset.remove});await loadMailboxes();await manager();};
$('add-mailbox-form').onsubmit=async e=>{e.preventDefault();try{const r=await api('add_mailbox',{email_address:$('new-mailbox-email').value,display_name:$('new-mailbox-name').value,mailbox_type:$('new-mailbox-type').value,staff_user_id:$('new-mailbox-staff').value||null});e.target.reset();await loadMailboxes();await manager();notice('Mailbox added to the system. Secure server credentials are still required before it can open its inbox.');}catch(err){notice(err.message,true);}};
$('mail-compose-form').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('[type="submit"]');btn.disabled=true;btn.textContent='SENDING...';try{await api('send',{mailbox_id:currentMailbox,to:$('compose-to').value,subject:$('compose-subject').value,text:$('compose-text').value});e.target.reset();$('mail-compose-form').hidden=true;$('mail-reader-empty').hidden=false;notice('Email sent successfully.');}catch(err){notice(err.message,true);}finally{btn.disabled=false;btn.textContent='SEND EMAIL';}};
});})();