(function(){
'use strict';let currentMailbox='default',currentFolder='INBOX',selectedUid=null,mailboxes=[];
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const addr=a=>(a||[]).map(x=>x.name?x.name+' <'+x.address+'>':x.address).join(', ');
const fmtDate=v=>{try{return v?new Date(v).toLocaleString('en-GB',{dateStyle:'short',timeStyle:'short'}):''}catch(_){return ''}};
function notice(t,bad=false){const e=$('mail-message');e.textContent=t||'';e.className='form-message '+(bad?'error':'success');}
async function api(action,payload={}){const sb=window.actionBuyerAuth?.supabase;if(!sb)throw Error('Secure connection unavailable.');const {data,error}=await sb.functions.invoke('management-mail-v2',{body:{action,...payload}});if(error)throw error;if(data?.error)throw Error(data.error);return data;}
async function guard(){const a=window.actionBuyerAuth,s=await a.getSession();if(!s){location.href='staff-login.html';return false;}const {data}=await a.supabase.from('staff_users').select('active,can_manage_staff').eq('user_id',s.user.id).maybeSingle();if(!data?.active||!data.can_manage_staff){location.href='admin.html';return false;}return true;}
function activeBox(){return mailboxes.find(x=>String(x.id)===String(currentMailbox))||mailboxes[0];}
async function loadMailboxes(){const d=await api('mailboxes');mailboxes=d.mailboxes||[];const sel=$('mailbox-select');sel.innerHTML=mailboxes.map(b=>'<option value="'+esc(b.id)+'">'+esc(b.display_name||b.email_address)+' — '+esc(b.email_address)+'</option>').join('');if(!mailboxes.some(b=>String(b.id)===String(currentMailbox)))currentMailbox=mailboxes[0]?.id||'default';sel.value=currentMailbox;const b=activeBox();$('mailbox-summary').innerHTML='<strong>'+esc(b?.display_name||'Business mailbox')+'</strong><span>'+esc(b?.email_address||'')+'</span>';$('compose-from-label').textContent='New message from '+(b?.email_address||'business mailbox');}
async function loadFolders(){const box=activeBox();$('mail-folders').innerHTML='<p style="padding:.5rem;color:#71808d">Loading folders...</p>';if(!box?.imapConfigured){$('mail-folders').innerHTML='<p style="padding:.5rem;color:#9a5a10;font-size:.82rem">Inbox connection pending for this mailbox.</p>';return;}const d=await api('folders',{mailbox_id:currentMailbox});const fs=d.folders||[];$('mail-folders').innerHTML='';fs.forEach(f=>{const b=document.createElement('button');b.type='button';b.className='mail-folder'+(f.path===currentFolder?' active':'');b.textContent=f.name;b.onclick=()=>{currentFolder=f.path;selectedUid=null;document.querySelectorAll('.mail-folder').forEach(x=>x.classList.toggle('active',x===b));loadMessages();};$('mail-folders').appendChild(b);});if(!fs.some(f=>f.path===currentFolder))currentFolder=fs[0]?.path||'INBOX';}
async function loadMessages(){const list=$('mail-list'),box=activeBox();$('mail-folder-title').textContent=currentFolder;$('mail-count').textContent='';if(!box?.imapConfigured){list.innerHTML='<div class="mail-empty"><div><strong>Mailbox connection pending</strong><p>Credentials for this address have not been configured yet.</p></div></div>';return;}list.innerHTML='<p style="padding:1rem">Loading messages...</p>';try{const d=await api('messages',{mailbox_id:currentMailbox,folder:currentFolder});$('mail-count').textContent=(d.total||0)+' messages';if(!d.messages?.length){list.innerHTML='<div class="mail-empty"><div><strong>No messages</strong><p>This folder is empty.</p></div></div>';return;}list.innerHTML='';d.messages.forEach(m=>{const b=document.createElement('button');b.type='button';b.className='mail-item'+(!m.seen?' unread':'')+(selectedUid===m.uid?' active':'');b.innerHTML='<div class="mail-item-row"><span class="mail-item-from">'+esc(m.from?.[0]?.name||m.from?.[0]?.address||'Unknown')+'</span><span>'+esc(fmtDate(m.date))+'</span></div><div class="mail-item-subject">'+esc(m.subject)+'</div>';b.onclick=()=>openMessage(m.uid,b);list.appendChild(b);});}catch(e){list.innerHTML='<p style="padding:1rem">Unable to load messages.</p>';notice(e.message,true);}}
async function openMessage(uid,button){selectedUid=uid;document.querySelectorAll('.mail-item').forEach(x=>x.classList.toggle('active',x===button));$('mail-compose-form').hidden=true;$('mail-reader-empty').hidden=true;$('mail-reader-content').hidden=false;$('mail-subject').textContent='Loading...';$('mail-meta').textContent='';$('mail-body').textContent='';try{const d=await api('message',{mailbox_id:currentMailbox,folder:currentFolder,uid});$('mail-subject').textContent=d.subject;$('mail-meta').textContent='From: '+addr(d.from)+'\nTo: '+addr(d.to)+'\n'+fmtDate(d.date);$('mail-body').textContent=decode(d.raw||'');}catch(e){$('mail-body').textContent='Unable to open this message.';notice(e.message,true);}}
function decode(raw){const p=raw.split(/\r?\n\r?\n/);if(p.length<2)return raw;let b=p.slice(1).join('\n\n');if(/content-transfer-encoding:\s*base64/i.test(p[0]))try{b=atob(b.replace(/\s/g,''));}catch(_){}return b.replace(/<[^>]+>/g,' ').replace(/\n{3,}/g,'\n\n').trim();}
function compose(){$('mail-reader-content').hidden=true;$('mail-reader-empty').hidden=true;$('mail-compose-form').hidden=false;$('compose-to').focus();}
async function manager(){const [mb,st]=await Promise.all([api('mailboxes'),api('staff')]);const staff=$('new-mailbox-staff');staff.innerHTML='<option value="">Not assigned</option>'+(st.staff||[]).map(s=>'<option value="'+s.user_id+'">'+esc(s.display_name||s.username)+(s.business_email?' — '+esc(s.business_email):'')+'</option>').join('');$('mailbox-cards').innerHTML=(mb.mailboxes||[]).map(b=>'<div class="mailbox-card"><div><strong>'+esc(b.display_name||b.email_address)+'</strong><small>'+esc(b.email_address)+' · '+esc(b.mailbox_type)+'</small></div><div><span class="mailbox-state '+((b.smtpConfigured&&b.imapConfigured)?'':'pending')+'">'+((b.smtpConfigured&&b.imapConfigured)?'CONNECTED':'SETUP PENDING')+'</span>'+(String(b.id)!=='default'?'<button class="btn btn-secondary mail-small-remove" data-remove="'+esc(b.id)+'" type="button">REMOVE</button>':'')+'</div></div>').join('');}
document.addEventListener('DOMContentLoaded',async()=>{if(!await guard())return;try{await loadMailboxes();await loadFolders();await loadMessages();}catch(e){notice(e.message,true);}
$('mailbox-select').onchange=async e=>{currentMailbox=e.target.value;currentFolder='INBOX';selectedUid=null;$('mail-reader-content').hidden=true;$('mail-reader-empty').hidden=false;await loadMailboxes();await loadFolders();await loadMessages();};
$('mail-refresh').onclick=async()=>{notice('');await loadFolders();await loadMessages();};$('mail-compose').onclick=compose;$('mail-compose-side').onclick=compose;
$('mail-cancel-compose').onclick=()=>{$('mail-compose-form').hidden=true;$('mail-reader-empty').hidden=false;};
$('manage-mailboxes').onclick=async()=>{$('mailbox-manager').hidden=false;await manager();};$('close-mailbox-manager').onclick=()=>{$('mailbox-manager').hidden=true;};
$('mailbox-cards').onclick=async e=>{const b=e.target.closest('[data-remove]');if(!b)return;if(!confirm('Remove this mailbox from GearCashOut?'))return;await api('remove_mailbox',{mailbox_id:b.dataset.remove});await loadMailboxes();await manager();};
$('add-mailbox-form').onsubmit=async e=>{e.preventDefault();try{const r=await api('add_mailbox',{email_address:$('new-mailbox-email').value,display_name:$('new-mailbox-name').value,mailbox_type:$('new-mailbox-type').value,staff_user_id:$('new-mailbox-staff').value||null});e.target.reset();await loadMailboxes();await manager();notice('Mailbox added to the system. Secure server credentials are still required before it can open its inbox.');}catch(err){notice(err.message,true);}};
$('mail-compose-form').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('[type="submit"]');btn.disabled=true;btn.textContent='SENDING...';try{await api('send',{mailbox_id:currentMailbox,to:$('compose-to').value,subject:$('compose-subject').value,text:$('compose-text').value});e.target.reset();$('mail-compose-form').hidden=true;$('mail-reader-empty').hidden=false;notice('Email sent successfully.');}catch(err){notice(err.message,true);}finally{btn.disabled=false;btn.textContent='SEND EMAIL';}};
});})();