document.addEventListener('DOMContentLoaded', async()=>{
  const auth=window.actionBuyerAuth, box=document.getElementById('return-box');if(!auth||!box)return;
  const session=await auth.getSession();if(!session){location.href='login.html?return=customer-return.html';return;}
  const saleId=new URLSearchParams(location.search).get('sale');const assetId=new URLSearchParams(location.search).get('asset');
  if(!saleId||!assetId){box.innerHTML='<p>No transaction was selected.</p>';return;}
  const db=auth.supabase;const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const {data:items,error}=await db.rpc('customer_get_returnable_items',{p_sale_id:saleId});
  if(error){box.innerHTML=`<p>${esc(error.message)}</p>`;return;}
  const item=(items||[]).find(x=>x.asset_id===assetId);
  if(!item){box.innerHTML='<p>This item is not available for a return request.</p>';return;}
  box.innerHTML=`<div class="valuation-card"><p class="section-kicker">TRANSACTION ${esc(item.transaction_number)}</p><h2>${esc([item.manufacturer,item.model].filter(Boolean).join(' '))}</h2><p><strong>Package:</strong> ${esc(item.package_name||'Not recorded')}</p><p><strong>Sale status:</strong> ${esc(item.status)}</p>${item.return_reference?`<div class="notice"><strong>Existing return</strong><br>${esc(item.return_reference)} · ${esc(item.return_status||'In progress')}</div>`:`<form id="return-form" class="auth-form" style="margin-top:1rem"><label>Why do you want to return this item?<textarea name="reason" rows="5" required placeholder="Please explain the reason for the return."></textarea></label><label>Additional information<textarea name="notes" rows="5" placeholder="Anything else you would like us to know?"></textarea></label><button class="btn btn-primary" type="submit">REQUEST RETURN</button><p id="return-message" class="form-message" aria-live="polite"></p></form>`}</div><div class="valuation-card" style="margin-top:1rem"><h3>What happens next</h3><ol><li>Your return reason is logged.</li><li>Our team will review it and may contact you to discuss the issue and try to resolve it without a return where appropriate.</li><li>If the return is accepted, we will provide return-label details.</li><li>When the item is received, it is checked before the return is authorised.</li></ol></div>`;
  const form=box.querySelector('#return-form');if(!form)return;
  form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form),button=form.querySelector('button'),message=form.querySelector('#return-message');button.disabled=true;message.textContent='Submitting return request…';message.className='form-message';const {data,error}=await db.rpc('customer_request_return',{p_asset_id:assetId,p_reason:String(fd.get('reason')||'').trim(),p_notes:String(fd.get('notes')||'').trim()||null});if(error){message.textContent=error.message;message.className='form-message error';button.disabled=false;return;}message.textContent=`Return request ${data?.return_reference||''} has been submitted. We will contact you after review.`;message.className='form-message success';form.innerHTML='<p>Your return request has been logged. Please check My Account for updates.</p>';});
});
