document.addEventListener("DOMContentLoaded", async () => {
  const auth = window.actionBuyerAuth;
  const container = document.getElementById("asset-detail");
  if (!auth || !container) return;
  const session = await auth.getSession();
  if (!session) { location.href = "login.html?return=inventory-detail.html"; return; }
  const db = auth.supabase;
  const { data: staff } = await db.from("staff_users").select("user_id").eq("user_id", session.user.id).maybeSingle();
  if (!staff) { container.innerHTML = "You do not have permission to access inventory."; return; }
  const id = new URLSearchParams(location.search).get("id");
  if (!id) { container.innerHTML = "No asset selected."; return; }
  const esc = v => String(v ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
  const date = v => v ? new Date(v).toLocaleString("en-GB") : "Not recorded";
  const checked = v => v ? "checked" : "";
  const conditions = { "factory-sealed":"Factory Sealed / Unopened", "opened-unused":"Opened but Unused", excellent:"Excellent", good:"Good", fair:"Fair", damaged:"Damaged", "not-working":"Not Working / Spares Only" };
  const conditionOptions = Object.entries(conditions).map(([v,l]) => `<option value="${v}">${l}</option>`).join("");
  const checklistNames = ["cleaned","photos","serial","accessories","batteries","reset","listing"];

  let asset;
  async function loadAsset() { const {data,error}=await db.from("inventory_assets").select("*").eq("id",id).single(); if(error||!data) throw new Error("Asset could not be found."); asset=data; }
  async function loadSource() { if(!asset.source_quote_item_id)return null; const {data}=await db.from("quote_items").select("id,item_name,package,item_data").eq("id",asset.source_quote_item_id).maybeSingle(); return data||null; }
  async function loadRecords() { const [testing,prep,evidence,listings]=await Promise.all([db.from("inventory_testing").select("*").eq("asset_id",id).order("created_at",{ascending:false}),db.from("inventory_preparation").select("*").eq("asset_id",id).order("created_at",{ascending:false}),db.from("inventory_evidence").select("*").eq("asset_id",id).eq("evidence_type","Photographs").order("created_at",{ascending:true}),db.from("resale_listings").select("*").eq("asset_id",id).order("sales_channel")]); return {testing:testing.data||[],preparation:prep.data||[],evidence:evidence.data||[],listings:listings.data||[]}; }
  async function signedUrls(records) { const paths=records.map(x=>x.file_url).filter(Boolean); if(!paths.length)return[]; const {data}=await db.storage.from("quote-photos").createSignedUrls(paths,3600); return (data||[]).map((x,i)=>({...x,record:records[i]})).filter(x=>x.signedUrl); }
  function testingEditor(r){return `<form class="auth-form inline-editor testing-editor" data-id="${r.id}"><label>Record type<select name="stage"><option value="inspection" ${r.stage==="inspection"?"selected":""}>Initial Inspection</option><option value="testing" ${r.stage!=="inspection"?"selected":""}>Technical Testing</option></select></label><label>Result<select name="result"><option value="">Not recorded</option><option ${r.result==="Passed"?"selected":""}>Passed</option><option ${r.result==="Requires Attention"?"selected":""}>Requires Attention</option><option ${r.result==="Failed"?"selected":""}>Failed</option></select></label><label>Physical condition<input name="visual_condition" value="${esc(r.visual_condition||"")}"></label><label><input type="checkbox" name="missing_items" ${checked(r.missing_items)}> Items missing</label><label>Damage / defects<textarea name="damage_notes" rows="3">${esc(r.damage_notes||"")}</textarea></label><label><input type="checkbox" name="serial_verified" ${checked(r.serial_verified)}> Serial verified</label><label><input type="checkbox" name="accessories_verified" ${checked(r.accessories_verified)}> Accessories verified</label><label>Flight<select name="flight_test"><option value="">Not recorded</option><option ${r.flight_test==="Passed"?"selected":""}>Passed</option><option ${r.flight_test==="Requires Attention"?"selected":""}>Requires Attention</option><option ${r.flight_test==="Failed"?"selected":""}>Failed</option><option ${r.flight_test==="Not Applicable"?"selected":""}>Not Applicable</option></select></label><label>Camera<select name="camera_test"><option value="">Not recorded</option><option ${r.camera_test==="Passed"?"selected":""}>Passed</option><option ${r.camera_test==="Requires Attention"?"selected":""}>Requires Attention</option><option ${r.camera_test==="Failed"?"selected":""}>Failed</option><option ${r.camera_test==="Not Applicable"?"selected":""}>Not Applicable</option></select></label><label>Battery<select name="battery_health"><option value="">Not recorded</option><option ${r.battery_health==="Good"?"selected":""}>Good</option><option ${r.battery_health==="Fair"?"selected":""}>Fair</option><option ${r.battery_health==="Requires Replacement"?"selected":""}>Requires Replacement</option><option ${r.battery_health==="Not Applicable"?"selected":""}>Not Applicable</option></select></label><label>Notes<textarea name="notes" rows="4">${esc(r.notes||"")}</textarea></label><button class="btn btn-primary" type="submit">SAVE CHANGES</button><p class="form-message editor-message" aria-live="polite"></p></form>`;}
  function preparationEditor(r){const c=r?.checklist||{};return `<form class="auth-form inline-editor preparation-editor" data-id="${r?.id||""}">${checklistNames.map(n=>`<label><input type="checkbox" name="${n}" ${checked(c[n])}> ${n.replace(/_/g," ")}</label>`).join("")}<label>Preparation notes<textarea name="notes" rows="5">${esc(r?.notes||"")}</textarea></label><button class="btn btn-primary" type="submit">SAVE PREPARATION DETAILS</button><p class="form-message editor-message" aria-live="polite"></p></form>`;}

  async function render(){
    await loadAsset(); const source=await loadSource(); const sourceData=source?.item_data&&typeof source.item_data==="object"?source.item_data:{}; const records=await loadRecords();
    const customerCondition=asset.customer_condition||sourceData.condition||sourceData.singleItem?.condition||""; const displayCustomerCondition=conditions[String(customerCondition).toLowerCase()]||customerCondition||"Not recorded";
    const customerMissing=Boolean(asset.customer_missing_items); const customerMissingDetails=asset.customer_missing_items_details||sourceData.exceptionNotes||""; const customerDamage=Boolean(asset.customer_damage); const customerNotes=asset.customer_exception_notes||sourceData.exceptionNotes||"";
    const photos=await signedUrls(records.evidence); const progress=window.AssetStateMachine?.getLifecycleProgress(asset.status||"Awaiting Receipt"); const nextStates=window.AssetStateMachine?.getAllowedNextStates(asset.status||"Awaiting Receipt")||[];
    let actions=""; if(asset.status==="Received")actions+=`<a class="btn btn-primary" href="inventory-testing.html?id=${encodeURIComponent(id)}&stage=inspection">START INSPECTION</a>`; if(asset.status==="Testing")actions+=`<a class="btn btn-primary" href="inventory-testing.html?id=${encodeURIComponent(id)}&stage=testing">OPEN TECHNICAL TESTING</a>`; if(asset.status==="Ready for Resale")actions+=`<a class="btn btn-primary" href="inventory-ready.html?id=${encodeURIComponent(id)}">RESALE PREPARATION</a><a class="btn btn-primary" href="listing-readiness.html?id=${encodeURIComponent(id)}">READY FOR SALE</a>`;
    container.innerHTML=`<div class="valuation-card"><p class="section-kicker">${esc(asset.status)}</p><h2>${esc([asset.manufacturer,asset.model].filter(Boolean).join(" "))}</h2><p>Asset reference: ${esc(asset.asset_reference)}</p><form id="asset-edit-form" class="auth-form"><label>Manufacturer<input name="manufacturer" value="${esc(asset.manufacturer||"")}"></label><label>Model<input name="model" value="${esc(asset.model||"")}"></label><label>Serial number<input name="serial_number" value="${esc(asset.serial_number||"")}"></label><label>Package<input name="package_name" value="${esc(asset.package_name||"")}"></label><label>Staff condition<select name="condition_grade"><option value="">Not recorded</option>${conditionOptions}</select></label><label>Purchase price<input name="purchase_price" type="number" min="0" step="0.01" value="${asset.purchase_price??""}"></label><label>Description<textarea name="description" rows="3">${esc(asset.description||"")}</textarea></label><label>Current location<input name="current_location" value="${esc(asset.current_location||"")}"></label><label>Expected battery count<input name="expected_battery_count" type="number" min="0" value="${asset.expected_battery_count??""}"></label><label>Actual battery count<input name="actual_battery_count" type="number" min="0" value="${asset.actual_battery_count??""}"></label><label>Approved resale price<input name="approved_resale_price" type="number" min="0" step="0.01" value="${asset.approved_resale_price??""}"></label><label>Internal notes<textarea name="notes" rows="4">${esc(asset.notes||"")}</textarea></label><button class="btn btn-primary" type="submit">SAVE ASSET DETAILS</button><p id="asset-edit-message" class="form-message" aria-live="polite"></p></form></div>
    <div class="valuation-card" style="margin-top:1rem"><h3>Customer information</h3><p><strong>Condition provided by customer:</strong> ${esc(displayCustomerCondition)}</p><p><strong>Missing items reported by customer:</strong> ${customerMissing?"Yes":"No"}</p>${customerMissing?`<p><strong>Customer missing-item details:</strong> ${esc(customerMissingDetails||"No details recorded")}</p>`:""}<p><strong>Damage reported by customer:</strong> ${customerDamage?"Yes":"No"}</p>${customerNotes?`<p><strong>Customer notes:</strong> ${esc(customerNotes)}</p>`:""}<p><strong>Customer serial:</strong> ${esc(sourceData.serialNumber||asset.serial_number||"Not recorded")}</p></div>
    <div class="valuation-card" style="margin-top:1rem"><h3>Asset Lifecycle</h3>${progress!==null&&progress!==undefined?`<p><strong>${progress}% complete</strong></p>`:""}<div style="display:flex;gap:.5rem;flex-wrap:wrap;margin-top:1rem">${actions}</div>${nextStates.length?`<div style="display:flex;gap:.5rem;flex-wrap:wrap;margin-top:1rem">${nextStates.map(s=>`<button type="button" class="btn btn-secondary lifecycle-action" data-state="${esc(s)}">${esc(s==="Held"?"HOLD ASSET":s)}</button>`).join("")}</div>`:""}<p id="state-message" class="form-message" aria-live="polite"></p></div>
    <div class="valuation-card" style="margin-top:1rem"><h3>Photographs (${photos.length})</h3>${photos.length?`<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:12px">${photos.map(x=>`<a href="${esc(x.signedUrl)}" target="_blank" rel="noopener"><img src="${esc(x.signedUrl)}" alt="Asset photograph" style="width:100%;height:150px;object-fit:cover;border-radius:8px"></a>`).join("")}</div>`:"<p>No photographs stored.</p>"}<p style="margin-top:1rem"><a class="btn btn-secondary" href="inventory-testing.html?id=${encodeURIComponent(id)}&stage=${asset.status==="Received"?"inspection":"testing"}">ADD / TAKE PHOTOGRAPHS</a></p></div>
    <div class="valuation-card" style="margin-top:1rem"><h3>Testing History</h3>${records.testing.length?records.testing.map(r=>`<article class="notice" style="margin-top:.75rem"><p><strong>${r.stage==="inspection"?"Initial Inspection":"Technical Testing"}</strong> · ${esc(date(r.created_at))}</p>${r.result?`<p><strong>Result:</strong> ${esc(r.result)}</p>`:""}${r.visual_condition?`<p><strong>Physical condition:</strong> ${esc(r.visual_condition)}</p>`:""}${r.missing_items!==null&&r.missing_items!==undefined?`<p><strong>Missing items:</strong> ${r.missing_items?"Yes":"No"}</p>`:""}${r.damage_notes?`<p><strong>Damage / defects:</strong> ${esc(r.damage_notes)}</p>`:""}${r.flight_test?`<p><strong>Flight:</strong> ${esc(r.flight_test)}</p>`:""}${r.camera_test?`<p><strong>Camera:</strong> ${esc(r.camera_test)}</p>`:""}${r.battery_health?`<p><strong>Battery:</strong> ${esc(r.battery_health)}</p>`:""}<p>${esc(r.notes||"No notes")}</p><button class="btn btn-secondary edit-testing" type="button" data-id="${r.id}">EDIT RECORD</button><div id="edit-testing-${r.id}" hidden></div></article>`).join(""):"<p>No inspection or testing records yet.</p>"}</div>
    <div class="valuation-card" style="margin-top:1rem"><h3>Resale Preparation</h3>${records.preparation.length?records.preparation.map(r=>`<article class="notice" style="margin-top:.75rem"><p><strong>Preparation record</strong> · ${esc(date(r.created_at))}</p><p>${esc(r.notes||"No preparation notes")}</p><p>${checklistNames.map(n=>`${n}: ${r.checklist?.[n]?"Yes":"No"}`).join(" · ")}</p><button class="btn btn-secondary edit-preparation" type="button" data-id="${r.id}">EDIT DETAILS</button><div id="edit-preparation-${r.id}" hidden></div></article>`).join(""):`<div id="new-preparation">${preparationEditor(null)}</div>`}</div>`;
    const cs=container.querySelector('[name="condition_grade"]'); if(cs)cs.value=asset.condition_grade||"";

    container.querySelector("#asset-edit-form").addEventListener("submit",async e=>{e.preventDefault();const f=e.target,fd=new FormData(f),m=f.querySelector("#asset-edit-message"),b=f.querySelector("button[type=submit]"),num=n=>fd.get(n)===""?null:Number(fd.get(n));b.disabled=true;m.textContent="Saving asset details…";const payload={manufacturer:String(fd.get("manufacturer")||"").trim()||null,model:String(fd.get("model")||"").trim()||null,serial_number:String(fd.get("serial_number")||"").trim()||null,package_name:String(fd.get("package_name")||"").trim()||null,condition_grade:String(fd.get("condition_grade")||"").trim()||null,purchase_price:num("purchase_price"),description:String(fd.get("description")||"").trim()||null,current_location:String(fd.get("current_location")||"").trim()||null,expected_battery_count:num("expected_battery_count"),actual_battery_count:num("actual_battery_count"),approved_resale_price:num("approved_resale_price"),notes:String(fd.get("notes")||"").trim()||null};const {error}=await db.from("inventory_assets").update(payload).eq("id",id);if(error){m.textContent=error.message;m.className="form-message error";b.disabled=false;return;}m.textContent="Asset details saved.";m.className="form-message success";setTimeout(render,250);});
    container.querySelectorAll(".edit-testing").forEach(btn=>btn.addEventListener("click",()=>{const r=records.testing.find(x=>x.id===btn.dataset.id),target=document.getElementById(`edit-testing-${btn.dataset.id}`);target.hidden=!target.hidden;if(target.hidden)return;target.innerHTML=testingEditor(r);target.querySelector("form").addEventListener("submit",async e=>{e.preventDefault();const f=e.target,fd=new FormData(f),m=f.querySelector(".editor-message"),b=f.querySelector("button[type=submit]");b.disabled=true;const {error}=await db.from("inventory_testing").update({stage:fd.get("stage"),result:fd.get("result")||null,visual_condition:fd.get("visual_condition")||null,missing_items:fd.get("missing_items")==="on",damage_notes:fd.get("damage_notes")||null,serial_verified:fd.get("serial_verified")==="on",accessories_verified:fd.get("accessories_verified")==="on",flight_test:fd.get("flight_test")||null,camera_test:fd.get("camera_test")||null,battery_health:fd.get("battery_health")||null,notes:fd.get("notes")||null,updated_by:session.user.id}).eq("id",r.id);if(error){m.textContent=error.message;m.className="form-message error";b.disabled=false;return;}m.textContent="Testing history updated.";m.className="form-message success";setTimeout(render,250);});}));
    container.querySelectorAll(".edit-preparation").forEach(btn=>btn.addEventListener("click",()=>{const r=records.preparation.find(x=>x.id===btn.dataset.id),target=document.getElementById(`edit-preparation-${btn.dataset.id}`);target.hidden=!target.hidden;if(target.hidden)return;target.innerHTML=preparationEditor(r);target.querySelector("form").addEventListener("submit",async e=>{e.preventDefault();const f=e.target,fd=new FormData(f),m=f.querySelector(".editor-message"),b=f.querySelector("button[type=submit]");b.disabled=true;const checklist=Object.fromEntries(checklistNames.map(n=>[n,fd.get(n)==="on"]));const {error}=await db.from("inventory_preparation").update({checklist,notes:fd.get("notes")||null}).eq("id",r.id);if(error){m.textContent=error.message;m.className="form-message error";b.disabled=false;return;}m.textContent="Preparation details updated.";m.className="form-message success";setTimeout(render,250);});}));
    container.querySelector("#new-preparation form")?.addEventListener("submit",async e=>{e.preventDefault();const f=e.target,fd=new FormData(f),m=f.querySelector(".editor-message"),b=f.querySelector("button[type=submit]");b.disabled=true;const checklist=Object.fromEntries(checklistNames.map(n=>[n,fd.get(n)==="on"]));const {error}=await db.from("inventory_preparation").insert({asset_id:id,checklist,notes:fd.get("notes")||null,completed_by:session.user.id});if(error){m.textContent=error.message;m.className="form-message error";b.disabled=false;return;}m.textContent="Preparation details added.";m.className="form-message success";setTimeout(render,250);});
    container.querySelectorAll(".lifecycle-action").forEach(btn=>btn.addEventListener("click",async()=>{const state=btn.dataset.state;if(state==="Held"&&!confirm("Place this asset on hold?"))return;btn.disabled=true;const m=document.getElementById("state-message");m.textContent=`Updating to ${state}…`;try{await window.AssetStateActions.transitionAsset(id,state,state==="Held"?"Asset placed on hold":"Staff lifecycle action");await render();}catch(err){m.textContent=err?.message||"Could not update asset status.";m.className="form-message error";btn.disabled=false;}}));
  }
  try{await render();}catch(err){container.innerHTML=`<p class="form-message error">${esc(err?.message||"Could not load asset")}</p>`;}
});
