document.addEventListener("DOMContentLoaded", async () => {
  const auth=window.actionBuyerAuth,list=document.getElementById("finance-list"),summary=document.getElementById("finance-summary");
  if(!auth||!list)return; const session=await auth.getSession(); if(!session){location.href="login.html?return=inventory-finance.html";return;} const db=auth.supabase;
  const {data:staff}=await db.from("staff_users").select("user_id").eq("user_id",session.user.id).maybeSingle(); if(!staff){list.innerHTML="<p>You do not have permission to access inventory.</p>";return;}
  const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"); const money=n=>Number(n||0).toLocaleString("en-GB",{style:"currency",currency:"GBP"});
  async function load(){
    const [{data:assets,error:aErr},{data:expenses,error:eErr},{data:listings,error:lErr}]=await Promise.all([db.from("inventory_assets").select("*").order("created_at",{ascending:false}),db.from("inventory_expenses").select("*").order("incurred_at",{ascending:false}),db.from("resale_listings").select("*").order("sales_channel")]);
    if(aErr||eErr||lErr){list.innerHTML=`<p>${esc(aErr?.message||eErr?.message||lErr?.message||"Could not load finance data.")}</p>`;return;}
    const expMap=new Map();(expenses||[]).forEach(x=>{if(!expMap.has(x.asset_id))expMap.set(x.asset_id,[]);expMap.get(x.asset_id).push(x);}); const listMap=new Map();(listings||[]).forEach(x=>{if(!listMap.has(x.asset_id))listMap.set(x.asset_id,[]);listMap.get(x.asset_id).push(x);});
    let realisedRevenue=0,realisedProfit=0,projectedProfit=0,totalStockCost=0;
    const cards=(assets||[]).map(a=>{const ex=expMap.get(a.id)||[],ls=listMap.get(a.id)||[],expenseTotal=ex.reduce((s,x)=>s+Number(x.amount||0),0),purchase=Number(a.purchase_price||0),sold=ls.find(x=>x.status==="Sold"),active=ls.find(x=>["Published","Reserved"].includes(x.status));const salePrice=sold?Number(sold.sold_price??sold.asking_price??0):0,fees=sold?Number(sold.selling_fees||0):0,shipping=sold?Number(sold.shipping_cost||0):0,totalCost=purchase+expenseTotal,profit=sold?salePrice-totalCost-fees-shipping:(active?Number(active.asking_price||0)-totalCost:null);totalStockCost+=a.status!=="Sold"?purchase+expenseTotal:0;if(sold){realisedRevenue+=salePrice;realisedProfit+=profit||0;}else if(profit!==null)projectedProfit+=profit;
      return `<article class="valuation-card" style="margin-bottom:1rem"><div style="display:flex;justify-content:space-between;gap:1rem;flex-wrap:wrap"><div><p class="section-kicker">${esc(a.status||"Purchased")}</p><h3><a href="inventory-detail.html?id=${encodeURIComponent(a.id)}">${esc([a.manufacturer,a.model].filter(Boolean).join(" ")||"Unnamed asset")}</a></h3><p>${esc(a.asset_reference)}</p></div><div><strong>${sold?"REALISED":"PROJECTED"} PROFIT</strong><br><span style="font-size:1.2rem">${profit===null?"Not priced":money(profit)}</span></div></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:1rem;margin-top:1rem"><div><strong>Purchase</strong><br>${money(purchase)}</div><div><strong>Extra costs</strong><br>${money(expenseTotal)}</div><div><strong>Total cost</strong><br>${money(totalCost)}</div><div><strong>Sale / target</strong><br>${sold?money(salePrice):active?money(active.asking_price):"Not listed"}</div><div><strong>Selling fees</strong><br>${money(fees)}</div><div><strong>Shipping</strong><br>${money(shipping)}</div></div><div style="margin-top:1rem"><h4>Additional costs</h4>${ex.length?`<ul>${ex.map(x=>`<li>${esc(x.category||"Other")}: ${money(x.amount)}${x.description?` — ${esc(x.description)}`:""}</li>`).join("")}</ul>`:"<p>No repair/additional costs recorded.</p>"}<form class="expense-form" data-id="${a.id}" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:.6rem;align-items:end"><label>Category<select name="category"><option>Repair</option><option>Parts</option><option>Accessories</option><option>Cleaning</option><option>Packaging</option><option>Listing</option><option>Shipping</option><option>Other</option></select></label><label>Amount<input name="amount" type="number" min="0" step="0.01" required></label><label>Description<input name="description"></label><button class="btn btn-secondary" type="submit">ADD COST</button></form><p class="form-message expense-message" aria-live="polite"></p></div></article>`;
    }).join("");
    summary.innerHTML=`<div style="display:flex;gap:2rem;flex-wrap:wrap"><div><strong>${money(totalStockCost)}</strong><br>active stock cost</div><div><strong>${money(realisedRevenue)}</strong><br>realised sales</div><div><strong>${money(realisedProfit)}</strong><br>realised profit</div><div><strong>${money(projectedProfit)}</strong><br>projected profit on priced stock</div></div>`; list.innerHTML=cards||"<p>No inventory.</p>";
    list.querySelectorAll(".expense-form").forEach(form=>form.addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(form),msg=form.querySelector(".expense-message"),button=form.querySelector("button");button.disabled=true;const {error}=await db.from("inventory_expenses").insert({asset_id:form.dataset.id,category:String(fd.get("category")),amount:Number(fd.get("amount")),description:String(fd.get("description")||"").trim()||null,incurred_at:new Date().toISOString()});if(error){msg.textContent=error.message;msg.className="form-message error";button.disabled=false;return;}load();}));
  }
  load();
});
