document.addEventListener("DOMContentLoaded", async () => {
  const auth = window.actionBuyerAuth;
  const box = document.getElementById("testing-form");
  if (!auth || !box) return;
  const session = await auth.getSession();
  if (!session) { location.href = "login.html?return=inventory-testing.html"; return; }
  const db = auth.supabase;
  const { data: staff } = await db.from("staff_users").select("user_id").eq("user_id", session.user.id).maybeSingle();
  if (!staff) { box.innerHTML = "No permission."; return; }
  const params = new URLSearchParams(location.search); const id = params.get("id"); const requestedStage = params.get("stage");
  if (!id) { box.innerHTML = "No asset selected."; return; }
  const { data: asset, error: assetError } = await db.from("inventory_assets").select("*").eq("id", id).single();
  if (assetError || !asset) { box.innerHTML = "Asset could not be found."; return; }
  const esc = v => String(v ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
  const loadScript = src => new Promise((resolve, reject) => { const s=document.createElement("script"); s.src=src; s.onload=resolve; s.onerror=reject; document.head.appendChild(s); });
  try { await loadScript("asset-state-machine.js?v=20260825-4"); await loadScript("asset-state-actions.js?v=20260825-4"); } catch (_) { box.innerHTML="Inventory workflow controls could not be loaded."; return; }

  async function getEvidence(){ const {data}=await db.from("inventory_evidence").select("*").eq("asset_id",id).eq("evidence_type","Photographs").order("created_at",{ascending:true}); return data||[]; }
  async function signedPhotoUrls(records){ const paths=records.map(x=>x.file_url).filter(Boolean); if(!paths.length)return[]; const {data}=await db.storage.from("quote-photos").createSignedUrls(paths,3600); return (data||[]).map((x,i)=>({...x,record:records[i]})).filter(x=>x.signedUrl); }
  async function photoSection(){ const records=await getEvidence(); const urls=await signedPhotoUrls(records); return `<div class="valuation-card" style="margin-top:1rem"><h3>Photographs</h3><p><strong>Customer photographs are retained as part of the asset record.</strong> Staff can add or take additional photographs below.</p>${urls.length?`<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:12px;margin:1rem 0">${urls.map(x=>`<a href="${esc(x.signedUrl)}" target="_blank" rel="noopener"><img src="${esc(x.signedUrl)}" alt="Asset photograph" style="width:100%;height:150px;object-fit:cover;border-radius:8px"></a>`).join("")}</div>`:"<p>No photographs are currently linked to this asset.</p>"}<form id="photo-form" class="auth-form"><label>Add / take inspection or resale photographs</label><input id="extra-photos" type="file" accept="image/*" capture="environment" multiple><p class="optional">On supported devices this can open the camera. On desktop, select image files.</p><button class="btn btn-primary" type="submit">UPLOAD PHOTOGRAPHS</button><p id="photo-message" class="form-message" aria-live="polite"></p></form></div>`; }
  async function uploadPhotos(files){ for(const file of files){ const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,"-"); const path=`${session.user.id}/inventory/${id}/${Date.now()}-${crypto.randomUUID()}-${safe}`; const {error}=await db.storage.from("quote-photos").upload(path,file,{contentType:file.type,upsert:false}); if(error)throw error; const {error:evidenceError}=await db.from("inventory_evidence").insert({asset_id:id,evidence_type:"Photographs",file_url:path,description:"Staff inspection / resale photograph",created_by:session.user.id}); if(evidenceError)throw evidenceError; } }
  function wirePhotoForm(){ const form=document.getElementById("photo-form"); if(!form)return; form.addEventListener("submit",async e=>{e.preventDefault();const m=document.getElementById("photo-message"),files=[...document.getElementById("extra-photos").files];if(!files.length){m.textContent="Select or take at least one photograph.";m.className="form-message error";return;}try{m.textContent="Uploading photographs…";await uploadPhotos(files);m.textContent="Photographs added to the asset record.";m.className="form-message success";setTimeout(()=>location.reload(),400);}catch(err){m.textContent=err?.message||"Could not upload photographs.";m.className="form-message error";}}); }

  let stage=requestedStage==="inspection"?"inspection":"testing";
  if(stage==="inspection"&&asset.status==="Received"){try{await window.AssetStateActions.transitionAsset(id,"Inspection Required","Initial inspection started on receipt");asset.status="Inspection Required";}catch(err){box.innerHTML=`<p class="form-message error">Could not start inspection: ${esc(err?.message||"Unknown error")}</p>`;return;}}
  if(stage==="inspection"&&!["Inspection Required","Received"].includes(asset.status)){box.innerHTML=`<h2>${esc([asset.manufacturer,asset.model].filter(Boolean).join(" ")||"Asset")}</h2><p>Current status: <strong>${esc(asset.status)}</strong></p><p>Initial inspection is only available when the asset has been received.</p>`;return;}
  if(stage==="testing"&&asset.status!=="Testing"){if(asset.status==="Inspection Required"){try{await window.AssetStateActions.transitionAsset(id,"Testing","Inspection completed; technical testing started");asset.status="Testing";}catch(err){box.innerHTML=`<p class="form-message error">Could not start technical testing: ${esc(err?.message||"Unknown error")}</p>`;return;}}else{box.innerHTML=`<h2>${esc([asset.manufacturer,asset.model].filter(Boolean).join(" ")||"Asset")}</h2><p>Current status: <strong>${esc(asset.status)}</strong></p><p>Technical testing can only be entered while the asset is in Testing.</p>`;return;}}

  if(stage==="inspection"){
    const customerCondition=asset.customer_condition||"Not recorded", customerMissing=Boolean(asset.customer_missing_items);
    box.innerHTML=`<h2>${esc([asset.manufacturer,asset.model].filter(Boolean).join(" ")||"Asset")}</h2><div class="valuation-card" style="margin:1rem 0"><h3>Customer information carried into inspection</h3><p><strong>Customer condition:</strong> ${esc(customerCondition)}</p><p><strong>Customer reported missing items:</strong> ${customerMissing?"Yes":"No"}</p>${customerMissing?`<p><strong>Customer missing-item details:</strong> ${esc(asset.customer_missing_items_details||"No details recorded")}</p>`:""}<p><strong>Customer reported damage:</strong> ${asset.customer_damage?"Yes":"No"}</p>${asset.customer_exception_notes?`<p><strong>Customer notes:</strong> ${esc(asset.customer_exception_notes)}</p>`:""}<p><strong>Package:</strong> ${esc(asset.package_name||"Not recorded")}</p></div><form id="inspection-form" class="auth-form"><label>Inspection result<select name="result"><option>Passed</option><option>Requires Attention</option><option>Failed</option></select></label><label>Physical condition observed by staff<input name="visual_condition" value="${esc(asset.condition_grade||"")}" placeholder="e.g. Good, signs of wear"></label><label><input type="checkbox" name="missing_items"> Items currently missing from package</label><label>Damage / defects observed<textarea name="damage_notes" rows="4"></textarea></label><label><input type="checkbox" name="serial_verified"> Serial number checked and verified</label><label><input type="checkbox" name="accessories_verified"> Accessories/package contents checked</label><label>Inspection notes<textarea name="notes" rows="5"></textarea></label><button class="btn btn-primary" type="submit">SAVE INSPECTION</button><p id="testing-message" class="form-message" aria-live="polite"></p></form>${await photoSection()}`;
    document.getElementById("inspection-form").addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(e.target),v={asset_id:id,stage:"inspection",result:fd.get("result"),visual_condition:String(fd.get("visual_condition")||"").trim(),missing_items:fd.get("missing_items")==="on",damage_notes:fd.get("damage_notes"),serial_verified:fd.get("serial_verified")==="on",accessories_verified:fd.get("accessories_verified")==="on",notes:fd.get("notes"),created_by:session.user.id},m=document.getElementById("testing-message"),b=e.target.querySelector("button[type=submit]");b.disabled=true;m.textContent="Saving inspection record…";const {error}=await db.from("inventory_testing").insert(v);if(error){m.textContent=error.message;m.className="form-message error";b.disabled=false;return;}const {error:assetError}=await db.from("inventory_assets").update({condition_grade:v.visual_condition||null}).eq("id",id);if(assetError){m.textContent=assetError.message;m.className="form-message error";b.disabled=false;return;}try{const next=v.result==="Passed"?"Testing":"Repair Required",updated=await window.AssetStateActions.transitionAsset(id,next,"Initial inspection completed");m.textContent=`Inspection saved. Asset moved to ${updated.status}.`;m.className="form-message success";e.target.innerHTML=`<p>Inspection saved. ${updated.status==="Testing"?"Technical testing can now be completed.":"The asset requires attention before testing."}</p>`;if(updated.status==="Testing")setTimeout(()=>location.href=`inventory-testing.html?id=${encodeURIComponent(id)}&stage=testing`,500);}catch(err){m.textContent=err?.message||"Could not update asset status.";m.className="form-message error";b.disabled=false;}});
    wirePhotoForm(); return;
  }

  box.innerHTML=`<h2>${esc([asset.manufacturer,asset.model].filter(Boolean).join(" ")||"Asset")}</h2><p><strong>Current status:</strong> ${esc(asset.status)}</p><form id="test-form" class="auth-form"><label>Flight test<select name="flight"><option>Passed</option><option>Requires Attention</option><option>Failed</option><option>Not Applicable</option></select></label><label>Camera test<select name="camera"><option>Passed</option><option>Requires Attention</option><option>Failed</option><option>Not Applicable</option></select></label><label>Battery health<select name="battery"><option>Good</option><option>Fair</option><option>Requires Replacement</option><option>Not Applicable</option></select></label><label>Testing notes<textarea name="notes" rows="6"></textarea></label><button class="btn btn-primary" type="submit">SAVE TEST</button><p id="testing-message" class="form-message" aria-live="polite"></p></form>${await photoSection()}`;
  document.getElementById("test-form").addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(e.target),v={asset_id:id,stage:"testing",flight_test:fd.get("flight"),camera_test:fd.get("camera"),battery_health:fd.get("battery"),notes:fd.get("notes"),created_by:session.user.id},m=document.getElementById("testing-message"),b=e.target.querySelector("button[type=submit]");b.disabled=true;m.textContent="Saving testing record…";const {error}=await db.from("inventory_testing").insert(v);if(error){m.textContent=error.message;m.className="form-message error";b.disabled=false;return;}const ok=(v.flight_test==="Passed"||v.flight_test==="Not Applicable")&&(v.camera_test==="Passed"||v.camera_test==="Not Applicable")&&(v.battery_health==="Good"||v.battery_health==="Not Applicable");try{const updated=await window.AssetStateActions.transitionAsset(id,ok?"Ready for Resale":"Repair Required","Technical testing record completed");m.textContent=`Testing saved. Asset moved to ${updated.status}.`;m.className="form-message success";e.target.innerHTML="Testing record saved and asset lifecycle updated.";}catch(err){m.textContent=err?.message||"Could not update asset status.";m.className="form-message error";b.disabled=false;}});
  wirePhotoForm();
});
