document.addEventListener('DOMContentLoaded',async()=>{
 const auth=window.actionBuyerAuth,list=document.getElementById('returns-list'),message=document.getElementById('returns-message');if(!auth||!list)return;
 const session=await auth.getSession();if(!session){location.href='login.html?return=returns.html';return;}const db=auth.supabase;const {data:staff}=await db.from('staff_users').select('user_id').eq('user_id',session.user.id).maybeSingle();if(!staff){list.innerHTML='<p>You do not have permission to manage returns.</p>';return;}
 const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');const date=v=>v?new Date(v).toLocaleString('en-GB'):'Not recorded';const money=v=>Number(v||0).toLocaleString('en-GB',{style:'currency',currency:'GBP'});
 async function load(){
  const [{data:returns,error},{data:assets},{data:sales}]=await Promise.all([db.from('customer_return_requests').select('*').order('created_at',{ascending:false}),db.from('inventory_assets').select('id,transaction_number,asset_reference,manufacturer,model,package_name,purchase_price,sold_price,sold_channel,status'),db.from('sales').select('id,sale_reference,user_id,total_amount')]);
  if(error){list.innerHTML=`<p>${esc(error.message)}</p>`;return;}const rs=returns||[];
  if(!rs.length){list.innerHTML='<div class="empty-account"><h3>No customer return requests</h3><p>Customer return requests will appear here.</p></div>';return;}
  list.innerHTML=rs.map(r=>{const a=(assets||[]).find(x=>x.id===r.asset_id)||{};const s=(sales||[]).find(x=>x.id===r.sale_id)||{};return `<article class="valuation-card" style="margin-bottom:1rem"><div style="display:flex;justify-content:space-between;gap:1rem;align-items:flex-start;flex-wrap:wrap"><div><p class="section-kicker">${esc(r.status)}</p><h2>${esc([a.manufacturer,a.model].filter(Boolean).join(' ')||'Returned product')}</h2><p><strong>Return:</strong> ${esc(r.return_reference)} · <strong>Transaction:</strong> ${esc(a.transaction_number||'Not recorded')}</p><p><strong>Sale:</strong> ${esc(s.sale_reference||'Not recorded')} · <strong>Customer ID:</strong> ${esc(r.customer_id)}</p></div><div><strong>Sold for</strong><br>${money(a.sold_price)}</div></div>
  <div class="notice" style="margin-top:1rem"><p><strong>Customer reason</strong><br>${esc(r.reason)}</p>${r.customer_notes?`<p><strong>Customer notes</strong><br>${esc(r.customer_notes)}</p>`:''}</div>
  <div class="notice" style="margin-top:1rem"><p><strong>Workflow dates</strong><br>Requested: ${esc(date(r.created_at))}<br>Negotiation: ${esc(date(r.negotiation_attempted_at))}<br>Accepted: ${esc(date(r.accepted_at))}<br>Label issued: ${esc(date(r.label_issued_at))}<br>Item received: ${esc(date(r.item_received_at))}<br>Authorised: ${esc(date(r.return_authorised_at))}<br>Refused: ${esc(date(r.refused_at))}</p>${r.label_tracking_number?`<p><strong>Return tracking:</strong> ${esc(r.label_carrier||'')} ${esc(r.label_tracking_number)}</p>`:''}${r.refusal_reason?`<p><strong>Refusal reason:</strong> ${esc(r.refusal_reason)}</p>`:''}</div>
  ${r.status==='Requested'||r.status==='Negotiation'?`<form class="action-form notice" data-id="${r.id}" data-action="negotiate" style="margin-top:1rem"><h3>Try to resolve before accepting return</h3><label>Negotiation / contact notes<textarea name="notes" rows="4" placeholder="Record what was discussed and whether the customer agreed to keep the item.">${esc(r.negotiation_notes||'')}</textarea></label><button class="btn btn-secondary" type="submit">LOG NEGOTIATION</button><button class="btn btn-primary accept-button" type="button" data-id="${r.id}">ACCEPT RETURN</button><button class="btn btn-secondary refuse-button" type="button" data-id="${r.id}">REFUSE RETURN</button><p class="form-message action-message" aria-live="polite"></p></form>`:''}
  ${r.status==='Accepted'?`<form class="label-form notice" data-id="${r.id}" style="margin-top:1rem"><h3>Send return label</h3><label>Label URL<input name="label_url" placeholder="Secure label URL"></label><label>Carrier<input name="carrier" placeholder="Royal Mail, Evri, DPD etc."></label><label>Tracking number<input name="tracking"></label><button class="btn btn-primary" type="submit">RECORD LABEL SENT</button><p class="form-message action-message" aria-live="polite"></p></form>`:''}
  ${r.status==='Label Sent'?`<div class="notice" style="margin-top:1rem"><strong>Label sent</strong><p>${esc(r.label_carrier||'Carrier not recorded')} · ${esc(r.label_tracking_number||'Tracking not recorded')}</p>${r.label_url?`<p><a class="btn btn-secondary" href="${esc(r.label_url)}" target="_blank" rel="noopener">OPEN LABEL</a></p>`:''}<button class="btn btn-primary received-button" data-id="${r.id}" type="button">MARK ITEM RECEIVED</button></div>`:''}
  ${r.status==='Item Received'?`<div class="notice" style="margin-top:1rem"><strong>Item received</strong><p>Complete the physical check, then authorise the return to move the complete product record into the Return Database.</p><button class="btn btn-primary authorise-button" data-id="${r.id}" type="button">AUTHORISE RETURN &amp; MOVE TO RETURN DATABASE</button><button class="btn btn-secondary refuse-button" data-id="${r.id}" type="button">REFUSE RETURN</button></div>`:''}
  ${r.status==='Return Refused'?`<form class="send-back-form notice" data-id="${r.id}" style="margin-top:1rem"><h3>Arrange sending the item back to customer</h3><label>Carrier<input name="carrier" value="${esc(r.return_to_customer_carrier||'')}"></label><label>Tracking number<input name="tracking" value="${esc(r.return_to_customer_tracking_number||'')}"></label><button class="btn btn-primary" type="submit">RECORD SENT BACK TO CUSTOMER</button><p class="form-message action-message" aria-live="polite"></p></form>`:''}
  ${r.status==='Return Sent Back'||r.status==='Return Authorised'?`<div class="form-message success" style="margin-top:1rem"><strong>${esc(r.status)}</strong>${r.status==='Return Authorised'?' — permanent return data record created.':' — outbound return recorded.'}</div>`:''}
  </article>`;}).join('');

  list.querySelectorAll('.action-form').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form);await act(form.dataset.id,'negotiate',{p_notes:String(fd.get('notes')||'').trim()});}));
  list.querySelectorAll('.accept-button').forEach(b=>b.addEventListener('click',()=>act(b.dataset.id,'accept',{p_notes:'Return accepted after staff review.'})));
  list.querySelectorAll('.refuse-button').forEach(b=>b.addEventListener('click',async()=>{const reason=prompt('Reason for refusing the return:');if(reason===null)return;await act(b.dataset.id,'refuse',{p_refusal_reason:reason,p_notes:'Customer contacted / refusal reason recorded.'});}));
  list.querySelectorAll('.label-form').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form);await act(form.dataset.id,'label',{p_label_url:String(fd.get('label_url')||'').trim(),p_label_carrier:String(fd.get('carrier')||'').trim(),p_label_tracking:String(fd.get('tracking')||'').trim(),p_label_issued_at:new Date().toISOString()});}));
  list.querySelectorAll('.received-button').forEach(b=>b.addEventListener('click',()=>act(b.dataset.id,'received',{})));
  list.querySelectorAll('.authorise-button').forEach(b=>b.addEventListener('click',async()=>{b.disabled=true;const {error}=await db.rpc('staff_authorise_customer_return',{p_return_id:b.dataset.id});if(error){alert(error.message);b.disabled=false;return;}load();}));
  list.querySelectorAll('.send-back-form').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form);await act(form.dataset.id,'sent_back',{p_return_to_customer_carrier:String(fd.get('carrier')||'').trim(),p_return_to_customer_tracking:String(fd.get('tracking')||'').trim()});}));
 }
 async function act(id,action,args){const {error}=await db.rpc('staff_update_customer_return',{p_return_id:id,p_action:action,...args});if(error){alert(error.message);return;}load();}
 await load();
});
